[project]
name = "fam-mcp"
version = "1.0.0"
description = "MCP server for FAM (Faculdade de Americana) University."
readme = "README.md"
authors = [
    { name = "Petri", email = "fernando.petri01@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "fastmcp>=4.0.10",
    "httpx>=0.28.1",
    "python-dotenv>=1.2.3",
]

[project.scripts]
fam-mcp = "fam_mcp:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
